# Site settings
title: ヒューリズム
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://noriok.github.io/" # the base hostname & protocol for your site
twitter_username: norioc
github_username:  noriok

# Build settings
# markdown: kramdown
markdown: redcarpet

